# Generated by Django 3.2.15 on 2022-08-16 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=64)),
                ('project_addres', models.URLField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todo_txt', models.TextField(blank=True)),
                ('todo_date_create', models.DateTimeField(auto_now_add=True)),
                ('todo_is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
